controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api

test:
    resource: ../../src/Test/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
