<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220922144916 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (1, NULL, 2, 300, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 7, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (6, NULL, 7, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 7, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (12, NULL, 8, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 7, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (13, 3, 2, 454, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (16, NULL, 9, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 7, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (17, 4, 2, 208, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (18, 5, 2, 100, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (19, NULL, 8, 16, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 9, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (22, NULL, 2, 60, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 7)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (23, NULL, 7, 2, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 7)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (24, NULL, 8, 3, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 7)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (25, NULL, 9, 3, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 7)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (26, NULL, 2, 300, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 10, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (27, NULL, 7, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 10, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (28, NULL, 8, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 10, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (29, NULL, 9, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 10, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (30, NULL, 2, 36, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 10)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (31, NULL, 7, 5, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 10)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (32, NULL, 8, 2, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 10)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (33, NULL, 9, 3, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 10)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (34, NULL, 2, 300, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 8, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (35, NULL, 7, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 8, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (36, NULL, 8, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 8, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (37, NULL, 9, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", 8, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (38, NULL, 2, 48, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 8)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (39, NULL, 7, 2, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 8)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (40, NULL, 8, 3, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 8)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (41, NULL, 9, 4, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, 8)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (42, NULL, 8, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 10, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (43, NULL, 8, 31, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 11, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (44, NULL, 8, 34, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 12, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (45, NULL, 8, 57, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 13, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (46, NULL, 2, 72, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 14, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (47, NULL, 8, 2, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 14, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (48, NULL, 2, 97, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 15, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (49, NULL, 8, 3, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 15, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (50, NULL, 2, 50, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 16, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (51, NULL, 8, 3, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 16, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (52, NULL, 2, 59, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 17, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (53, NULL, 8, 2, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 17, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (54, NULL, 2, 84, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 18, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (55, NULL, 8, 4, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 18, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (56, NULL, 2, 98, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 19, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (57, NULL, 8, 4, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 19, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (58, NULL, 2, 239, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 20, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (59, NULL, 8, 6, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 20, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (60, NULL, 2, 214, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 21, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (61, NULL, 8, 6, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 21, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (62, NULL, 2, 117, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 22, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (63, NULL, 8, 3, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 22, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (66, NULL, 2, 130, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 23, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (67, NULL, 8, 3, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 23, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (68, NULL, 2, 79, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 24, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (69, NULL, 8, 4, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 24, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (70, NULL, 2, 118, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 25, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (71, NULL, 8, 4, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, 25, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (73, 4, 8, 16, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (74, 12, 2, 256, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (75, 12, 9, 21, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (76, 13, 2, 278, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (77, 13, 7, 25, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (78, 3, 7, 61, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (79, 14, 2, 716, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (80, 14, 8, 51, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (81, 15, 2, 1091, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (82, 15, 8, 77, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (84, 16, 2, 584, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (85, 16, 9, 55, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (86, 17, 2, 519, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
        $this->addSql('INSERT IGNORE INTO bind_characteristic (id, monster_id, characteristic_id, amount, created_at, updated_at, base_academy_id, item_id, academy_id) VALUES (87, 17, 7, 70, "'.date_create()->format('Y-m-d H:i:s').'", "'.date_create()->format('Y-m-d H:i:s').'", NULL, NULL, NULL)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
